### ISSUE TITLE
Try gulp-twig as replacement for gulp-swig

### ISSUE THREAD

**Issue by mortenc** [taracila/prototype#1]
Since Drupal 8 will be using Twig, we should test if we can find a gulp plugin for Twig instead of the current gulp-swig. This may be an option:

https://www.npmjs.com/package/gulp-twig

While Swig and Twig are similar, there may be some [small syntax differences](https://www.joshwillik.com/blog/twig-not-equal-swig/), so it would probably be good not to mix the two, but stick with one of them?

**Comment by taracila** [comment]
@mortenc I've added changes. Please test https://github.com/taracila/prototype/pull/2 and tell me how it runs on your end.

Thanks

**Comment by taracila** [comment]
https://github.com/taracila/prototype/pull/2 PR has fixed this issue.
